# Generated by Django 3.1.5 on 2021-02-04 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210203_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'PRODUCT', 'verbose_name_plural': 'PRODUCT'},
        ),
    ]
