# Generated by Django 3.1.5 on 2021-02-04 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0003_auto_20210130_0839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fcuser',
            options={'verbose_name': 'FCUSER', 'verbose_name_plural': 'FCUSER'},
        ),
    ]
