# Generated by Django 3.1.5 on 2021-02-04 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0004_auto_20210204_0645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fcuser',
            options={'verbose_name': 'fcuser', 'verbose_name_plural': 'fcuser'},
        ),
    ]
