# Generated by Django 3.1.5 on 2021-01-27 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'order', 'verbose_name_plural': 'order'},
        ),
        migrations.AlterModelTable(
            name='order',
            table='fc_order',
        ),
    ]
