# Generated by Django 3.1.5 on 2021-02-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210127_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='Memo'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='waiting', max_length=32, verbose_name='Status'),
        ),
    ]
