# Generated by Django 3.1.5 on 2021-02-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210203_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('payment', 'payment'), ('refund', 'refund')], default='waiting', max_length=32, verbose_name='Status'),
        ),
    ]
