# Generated by Django 3.1.5 on 2021-02-04 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210203_0853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'ORDER', 'verbose_name_plural': 'ORDER'},
        ),
    ]
